version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my_producer_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobportal
    ports:
      - "5050:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
   
    
  app:
    build: .
    container_name: my_producer_app_container
    ports:
      - "8081:9002"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_producer_postgres_container:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my-network
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
     
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      #KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_AUTO_CRREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "userBulk:1:1"
      
 
  
volumes:
  postgres-data:
