version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my_producer_postgres_container1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobportal
    ports:
      - "5054:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - some-net

  app:
    build: .
    container_name: my_producer_app_container1
    ports:
      - "8082:9002"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_producer_postgres_container1:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - some-net
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper1
    ports:
      - "2182:2182"
    networks:
      - some-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9094" 
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181 
      KAFKA_CREATE_TOPICS: "userBulk:1:1"
    networks:
      - some-net

volumes:
  postgres-data:

networks:
  some-net:
    driver: bridge
