version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobportal
    ports:
      - "5050:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_app_container
    ports:
      - "8081:9002"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

       
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 9514
      
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 5.189.191.68
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:9514
      KAFKA_AUTO_CRREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "userBulk:1:1"
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 300000
    volumes:
      - ntts-kafka:/var/run/docker.sock 
          
volumes:
  postgres-data:
