version: '3.8'

service:
   postgres :
    images: postgres:latest
    container_name: job_db
    restart: always
    enviroment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: root
     POSTGRES_DB: jobportal
     ports:
       -"5050:5432"
     volumes: 
       - postgres-data:/var/lib/postgresql/data
       
     application:
     build :
     container_name: job_portal_Application
     ports : 
        - "8081:9002"
    depends_on:
        - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
       
      
      
    

 
