version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobportal
    ports:
      - "5050:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      
      
  app:
    build: .
    container_name: my_app_container
    ports:
      - "8081:9002"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
   
#  redis:
#    container_name: "redis_job_portal"
#    restart: always
#    command: redis-server
#    sysctls:
#      - net.core.somaxconn=65535
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    image: redis:latest
#    ports:
#      - 6379:6379
    zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      
    kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: <your-hostname>
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.200:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CREATE_TOPICS: "userBulk"
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 300000

volumes:
  postgres-data:







