version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my_producer_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobportal
    ports:
      - "5050:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_producer_app_container
    ports:
      - "8081:9002"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_producer_postgres_container:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  zookeeper:
     image: wurstmeister/zookeeper
     ports:
       - "2181:2181"

  kafka:
     image: wurstmeister/kafka
     ports:
       - "9092:9092"
     environment:
       KAFKA_BROKER_ID: 1
       KAFKA_ADVERTISED_HOST_NAME: localhost
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:9514
       KAFKA_AUTO_CRREATE_TOPICS_ENABLE: "true"
       KAFKA_CREATE_TOPICS: "userBulk:1:1"
      # KAFKA_CREATE_TOPICS: "topicBulk:1:1"
       KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 300000
     volumes:
       - job_portal-kafka:/var/run/docker.sock



volumes:
  postgres-data:
