version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my_producer_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobportal
    ports:
      - "5050:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_producer_app_container
    ports:
      - "8081:9002"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_producer_postgres_container:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
  
  zookeeper:
    ports:
      - '50000:2181'
    image: zookeeper:3.5.9
   
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'INTERNAL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_CREATE_TOPICS: 'userBulk:1:1'
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1 # change to 172.17.0.1 if running on Ubuntu
    image: 'wurstmeister/kafka:2.13-2.8.1'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  


volumes:
  postgres-data:
  job_portal-kafka:
