version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my_producer_postgres_container1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobportal
    ports:
      - "5054:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_producer_app_container1
    ports:
      - "8082:9008"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_producer_postgres_container:5432/jobportal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper1
    ports:
      - "2182:2181"
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_CREATE_TOPICS: "userBulk:1:1"
    depends_on:
      - zookeeper
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
